version: "3.8"

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    # hostname: traefik
    command:
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--log.level=INFO"
      - "--ping=true"
      - "--api.dashboard=${TRAEFIK_DASHBOARD_ENABLE}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.cloudflare.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.caServer=${TRAEFIK_ACME_CASERVER}"
      - "--certificatesresolvers.cloudflare.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.network=${TRAEFIK_PROXY_NETWORK}"
    labels:
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_URL}`)"
        - "traefik.http.routers.dashboard.entrypoints=traefik"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/var/traefik/certs:rw
    environment:
      - TZ=America/New_York
      #- CF_DNS_API_TOKEN=
      - CF_DNS_API_TOKEN_FILE=/run/secrets/traefik_token
    networks:
      - proxy
    secrets:
      - source: traefik_token
        target: /run/secrets/traefik_token
      - source: middlewares_users
        target: /etc/traefik/users
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.traefik == true

secrets:
  traefik_token:
    external: true
    name: ${CF_API_TOKEN_SECRET_NAME}
  middlewares_users:
    external: true
    name: ${TRAEFIK_MIDDLEWARES_USERS_NAME}

networks:
  proxy:
    driver: overlay
    attachable: true
    name: proxy

volumes:
  traefik_certs:
    driver: local